# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2022 Suguru Saito <sg.sgch07@gmail.com>
#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.

obj-y  := mx6dl40s404.o ../../freescale/common/pfuze.o
